[platformio]
default_envs = esp32c6-sdio-worker

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 8MB
board_build.partitions = max_app_8MB.csv
lib_deps =
    bblanchon/ArduinoJson@^7.4.2
build_flags =
    -Iinclude
    -I../include

[env:esp32c6-sdio-worker]
extends = env:esp32c6
build_flags =
    ${env:esp32c6.build_flags}
    -DC6_WORKER_TRANSPORT=2

[env:esp32c6-wifi-debug]
extends = env:esp32c6-sdio-worker
build_flags =
    ${env:esp32c6-sdio-worker.build_flags}
    -DC6_WORKER_DEBUG_SERIAL=1
    -DC6_WORKER_ENABLE_BINARY_SNAPSHOT_STREAM=0

[env:esp32c6-uart-worker]
extends = env:esp32c6
build_flags =
    ${env:esp32c6.build_flags}
    -DC6_WORKER_TRANSPORT=1
