#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#if defined(__has_include)
#if __has_include("app_secrets.h")
#include "app_secrets.h"
#endif
#endif

#ifndef LONDONBRIEF_WIFI_SSID
#define LONDONBRIEF_WIFI_SSID "YOUR_WIFI_SSID"
#endif

#ifndef LONDONBRIEF_WIFI_PASSWORD
#define LONDONBRIEF_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#endif

#ifndef LONDONBRIEF_TFL_APP_KEY
#define LONDONBRIEF_TFL_APP_KEY ""
#endif

#ifndef LONDONBRIEF_LOCATION_NAME
#define LONDONBRIEF_LOCATION_NAME "London"
#endif

#ifndef LONDONBRIEF_LATITUDE
#define LONDONBRIEF_LATITUDE 51.5072
#endif

#ifndef LONDONBRIEF_LONGITUDE
#define LONDONBRIEF_LONGITUDE -0.1276
#endif

#ifndef LONDONBRIEF_NEWS_RSS_URL
#define LONDONBRIEF_NEWS_RSS_URL "https://feeds.bbci.co.uk/news/rss.xml?edition=uk"
#endif

#ifndef LONDONBRIEF_TLS_ROOT_CA
#define LONDONBRIEF_TLS_ROOT_CA ""
#endif

#ifndef LONDONBRIEF_ALLOW_INSECURE_TLS
#if defined(LONDONBRIEF_LAB_ALLOW_INSECURE_TLS) && LONDONBRIEF_LAB_ALLOW_INSECURE_TLS
#define LONDONBRIEF_ALLOW_INSECURE_TLS 1
#else
#define LONDONBRIEF_ALLOW_INSECURE_TLS 0
#endif
#endif

#ifndef LONDONBRIEF_TFL_FAVORITE_1
#define LONDONBRIEF_TFL_FAVORITE_1 "Elizabeth line"
#endif

#ifndef LONDONBRIEF_TFL_FAVORITE_2
#define LONDONBRIEF_TFL_FAVORITE_2 "Northern"
#endif

#ifndef LONDONBRIEF_TFL_FAVORITE_3
#define LONDONBRIEF_TFL_FAVORITE_3 "Victoria"
#endif

#ifndef LONDONBRIEF_TFL_FAVORITE_4
#define LONDONBRIEF_TFL_FAVORITE_4 "Central"
#endif

#ifndef LONDONBRIEF_NETWORK_MODE
#define LONDONBRIEF_NETWORK_MODE 0
#endif

#ifndef LONDONBRIEF_DATA_SOURCE
#define LONDONBRIEF_DATA_SOURCE 0
#endif

#ifndef LONDONBRIEF_C6_TRANSPORT
#define LONDONBRIEF_C6_TRANSPORT 0
#endif

#ifndef LONDONBRIEF_WIFI_DEBUG
#define LONDONBRIEF_WIFI_DEBUG 0
#endif

#ifndef LONDONBRIEF_SERVICE_DEBUG
#define LONDONBRIEF_SERVICE_DEBUG 0
#endif

#ifndef LONDONBRIEF_ENABLE_PIXEL_ART
#define LONDONBRIEF_ENABLE_PIXEL_ART 1
#endif

#ifndef LONDONBRIEF_C6_SERIAL_BAUD
#define LONDONBRIEF_C6_SERIAL_BAUD 115200
#endif

#ifndef LONDONBRIEF_C6_SERIAL_PORT
#define LONDONBRIEF_C6_SERIAL_PORT 1
#endif

#ifndef LONDONBRIEF_C6_SERIAL_RX_PIN
#define LONDONBRIEF_C6_SERIAL_RX_PIN -1
#endif

#ifndef LONDONBRIEF_C6_SERIAL_TX_PIN
#define LONDONBRIEF_C6_SERIAL_TX_PIN -1
#endif

#ifndef LONDONBRIEF_ENABLE_BATTERY_MONITOR
#define LONDONBRIEF_ENABLE_BATTERY_MONITOR 0
#endif

#ifndef LONDONBRIEF_BATTERY_DIVIDER_RATIO
#define LONDONBRIEF_BATTERY_DIVIDER_RATIO 1.68f
#endif

#ifndef LONDONBRIEF_BATTERY_EMPTY_V
#define LONDONBRIEF_BATTERY_EMPTY_V 3.30f
#endif

#ifndef LONDONBRIEF_BATTERY_FULL_V
#define LONDONBRIEF_BATTERY_FULL_V 4.20f
#endif

#endif
